### ISSUE TITLE
[undefined] Unexpected token const...

### ISSUE THREAD

**Issue by peteruithoven** [peol/brackets-eslint#10]
When using `const` ESLint seems to stop on the first occurrence of `const` in my code. I checked [ESLint's rules](http://eslint.org/docs/rules/) and there seem to be no rules that could cause that. 
It displays the problem:
```
[undefined] Unexpected token const	const ApiBase = require('../ApiBase');
```

**Comment by peol** [comment]
You need to enable `blockBindings` in your `.eslintrc` file:
```js
	"ecmaFeatures": {
		"blockBindings": true
	},
```

See more here:
http://eslint.org/docs/configuring/#specifying-language-options

**Comment by peteruithoven** [comment]
Awesome, that works.

Peter

**Comment by strawherotk** [comment]
Hi guys,
Could you please tell me more why ESLint categorize this at an error?
I think there's no reason to categorize const declaration as error?

thanks.
