### ISSUE TITLE
Support non relative paths

### ISSUE THREAD

**Issue by AdriVanHoudt** [peol/brackets-eslint#11]
The relative path works fine for defining the location of the `.eslintrc` file for a certain project but not for the global preference. Since I want to use 1 config for global as a fallback and some projects are in a deeper folder structure this is just not possible. If you can define an absolute path to a global fallback that would work way better.

**Comment by peol** [comment]
To be honest, I already thought it worked like that (I know I wrote the code for it a while back) but it's obviously not on GitHub yet :) I'll get it sorted once work clears up a bit.

**Comment by AdriVanHoudt** [comment]
:+1: thanks!

**Comment by AdriVanHoudt** [comment]
Any eta on this?

**Comment by peol** [comment]
Work still taking up a lot of my time. I might be able to squeeze it in this weekend but I can't promise anything I'm afraid.

**Comment by AdriVanHoudt** [comment]
No problem!
