### ISSUE TITLE
Brackets 1.2 deprecation warnings

### ISSUE THREAD

**Issue by AdriVanHoudt** [peol/brackets-eslint#13]
```javascript
 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.<anonymous> (file:///C:/Users/adri/AppData/Roaming/Brackets/extensions/user/peolanha.brackets-eslint/main.js:86:2)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
```

Should be an easy fix

**Comment by peol** [comment]
I'm diverting users to https://github.com/zaggino/brackets-eslint which fills the exact same functionality and is better maintained. Thanks for your support :)

**Comment by AdriVanHoudt** [comment]
Only I can't install it via Brackets .__.

**Comment by peol** [comment]
If I understand @zaggino correctly, you should be able to update it through: https://github.com/zaggino/brackets-npm-registry

**Comment by AdriVanHoudt** [comment]
yeah but why would I want that? Brackets has a built in registry

**Comment by zaggino** [comment]
Built-in registry can't download dependencies from npm and run build scripts, that's why `brackets-npm-registry` exists. `brackets-eslint` uses the same exact version of the eslint, which is in npm with few other dependencies. It's not possible to upload these dependencies to built-in registry due to its restrictions.

**Comment by AdriVanHoudt** [comment]
hmm I see, is this an issue that Brackets owners/contributors are aware of?

**Comment by zaggino** [comment]
Yes, I've also opened a PR with a lighter version of this (downloads dependencies, but can't run build scripts) for a default registry (https://github.com/adobe/brackets/pull/10602).

**Comment by AdriVanHoudt** [comment]
@zaggino nice, might want to bump the PR with a reaction on @nethip's questions or something
