### ISSUE TITLE
Unable to use custom parser

### ISSUE THREAD

**Issue by globexdesigns** [peol/brackets-eslint#14]
I have the following defined in my .eslintrc

```
parser: esprima-fb
```

The esprima parser was installed via `npm install esprima-fb`. This works just fine when running ESLint manually, or via grunt-eslint, but brackets-eslint doesn't seem to like that I've defined a custom parser because it shows:

```
[undefined] Cannot find module `esprima-fb`
```

**Comment by peol** [comment]
I recommend you switch over to https://github.com/zaggino/brackets-eslint instead, he's more actively maintaining his extension (I'll be sunsetting this in favour of @zaggino's)

**Comment by zaggino** [comment]
thanks @peol , appreciated ... hopefully `brackets-npm-registry` which is needed to install my version will work for users, it hasn't been widely tested
