### ISSUE TITLE
Uses local .eslintrc right?

### ISSUE THREAD

**Issue by peteruithoven** [peol/brackets-eslint#4]
Just to be sure, it uses the `.eslintrc` file in the current project right?

**Comment by peol** [comment]
Currently, the extension does not automatically read inherited `.eslintrc` (like the command-line tool does), you'd need to specify the location of your `.eslintrc` for it to work properly.

**Comment by peteruithoven** [comment]
Why not? Wouldn't that be a useful default?

**Comment by peol** [comment]
Yes, I'll add it to a new list of "missing features".

**Comment by mtscout6** [comment]
how exactly do you configure it?
