### ISSUE TITLE
Update version of ESLint?

### ISSUE THREAD

**Issue by briandipalma** [peol/brackets-eslint#6]
The new rules are causing the plugin not to work...

**Comment by peol** [comment]
I've bumped the version now, however, the extension registry is currently down so you'd have to wait until it's back up so that I can upload a new version.

**Comment by briandipalma** [comment]
Cool, thanks.

**Comment by peol** [comment]
New version uploaded. I'll close this issue, please re-open if you still have issues (with a bit more details).
