### ISSUE TITLE
Compatible with Interactive linter?

### ISSUE THREAD

**Issue by peteruithoven** [peol/brackets-eslint#7]
Is this extension compatible with the [Interactive linter extension](https://github.com/MiguelCastillo/Brackets-InteractiveLinter)? 
I cloned the repository to my `Application Support/Brackets/extensions/user` folder, to make sure I have the latest version. 
I don't see the errors in the interactive linter panel I see without the extension in the report panel.

**Comment by peol** [comment]
I have no idea. This extension registers as a linter for JavaScript and follows the normal API's (reporting the errors back to Brackets), if that project uses those API's, I guess it should work. :)

**Comment by peteruithoven** [comment]
Thanks for your response. It does work with the [EPIC linter](https://github.com/fdecampredon/brackets-epic-linter). I'll report it with the people behind the interactive linter.

**Comment by peol** [comment]
Thanks :)
