### ISSUE TITLE
Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by AdriVanHoudt** [peol/brackets-eslint#8]
The new update breaks on https://github.com/peol/brackets-eslint/blob/master/main.js#L47
It returns an empty object.

**Comment by peol** [comment]
Do you have a file that triggers this? Seems to be working fine for me :/

**Comment by AdriVanHoudt** [comment]
Every js file triggers it, also the plugins times out but that is because of the error I assume

**Comment by AdriVanHoudt** [comment]
Hmm not stringifying the message in the wrapper and then not parsing that in the main.js seems to work.

**Comment by AdriVanHoudt** [comment]
w8 not stringifying but do parsing. I think I'm not debugging right with the domain manager but nevertheless it has to do something with that

**Comment by AdriVanHoudt** [comment]
uninstall and reinstall breaks it again :neutral_face:

**Comment by AdriVanHoudt** [comment]
I think I found the problem with the cli of eslint. The new version deprecated the `space-unary-word-ops` and the plugin doesn't throw eslint errors. And I had a `.eslintrc` file in an above folder that eslint somehow seemed to prefered. 
Would there be a way for the plugin to throw/show eslint errors?

**Comment by peol** [comment]
Yeah, I'll create a new issue about that. Cheers
